name: Deploy to GCP

on:
  push:
    branches:
      - main     #run auto when we push to main (dev) branch
  workflow_dispatch:  # this is Manual trigger for prod 

jobs:
  deploy-dev:
    name: Deploy to Dev
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

        #No json key files in secrets - better security then service account
      - name: Authenticate to Google Cloud using OIDC (Workload Identity Federation)
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }} 
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }} 
          service_account: ${{ secrets.SERVICE_ACCOUNT }} 

      # this is used to install gsutil to make bucket for state file 
      - name: Set up Cloud SDK 
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: 'gsutil'                

      - name: Make tf state bucket if its missing 
        shell: bash
        run: |
            BUCKET="gs://tf-state-${{ secrets.PROJECT_ID }}"
            gsutil ls -b "$BUCKET" >/dev/null 2>&1 && exit 0   
            gsutil mb -p "${{ secrets.PROJECT_ID }}" -l us-central1 "$BUCKET"
            gsutil versioning set on "$BUCKET"
        

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: '1.5.0'    

      - name: Install Terragrunt
        run: |
          curl -sLo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.41.0/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: Initialize and Apply with Terragrunt (Dev)
        run: |
          cd live/dev
          terragrunt init
          terragrunt apply -auto-approve

  deploy-prod:
    name: Deploy to Prod
    runs-on: ubuntu-latest
    needs: deploy-dev
    environment: production  # requires manual approval in UI github 
    permissions:
      contents: 'read'
      id-token: 'write'  

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to Google Cloud using OIDC (Workload Identity Federation)
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }} 
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }} 
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
 
      
      - name: Set up Cloud SDK 
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          install_components: 'gsutil'          
          
      - name: Make TF state bucket if its missing 
        shell: bash
        run: |
              BUCKET="gs://tf-state-${{ secrets.PROJECT_ID }}"
              gsutil ls -b "$BUCKET" >/dev/null 2>&1 && exit 0
              gsutil mb -p "${{ secrets.PROJECT_ID }}" -l us-central1 "$BUCKET"
              gsutil versioning set on "$BUCKET"

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform_version: '1.5.0'    

      - name: Install Terragrunt
        run: |
          curl -sLo terragrunt https://github.com/gruntwork-io/terragrunt/releases/download/v0.41.0/terragrunt_linux_amd64
          chmod +x terragrunt
          sudo mv terragrunt /usr/local/bin/terragrunt

      - name: Initialize and Apply with Terragrunt (Prod)
        run: |
          cd live/prod
          terragrunt init
          terragrunt apply -auto-approve
